10th Sprint 1st push
ArseniiYanovskyi/java-filmorate pull request #6
Opened 2023-06-17 12:50 UTC by ArseniiYanovskyi

2023-06-17 21:26 UTC, Yang-Pi requested changes

2023-06-17 21:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse("NOT_FOUND_ERROR", e.getMessage());
Не хватает еще логирования сообщения об ошибке, чтобы на стороне сервиса тоже была эта информация для мониторинга.

2023-06-17 21:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmService.getOptionalOfRequiredFilmById(filmId).isEmpty()) {
Подобные валидации лучше перенести в класс сервиса, тк это тоже часть бизнес-логики - 1) определение неверных данных 2) реакция на неверные данные

2023-06-17 21:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        Film film = filmRepository.getOptionalOfFilmById(filmId).get();
Ты используешь Optional в качестве возвращаемого типа, но при этом никак это не используешь, и на 42й строке вполне можешь упасть с NPE.

2023-06-18 10:35 UTC, ArseniiYanovskyi commented
привет) сделал новый класс в сервисе, Validator, он проверяет корректность передаваемого объекта, наличие в репозитории искомого объекта, по логике открытие Optional не должно происходить перед валидацией этого класса, и по этой причине я не добавил проверку перед открытием Optional в сервисе. Правильно ли так, или добавить всю проверку валидации непосредственно в сервисы?

2023-06-18 14:38 UTC, Yang-Pi requested changes

2023-06-21 12:39 UTC, Yang-Pi approved these changes

2023-06-24 12:31 UTC, merged